# Use the official Apify base image with Node.js and Puppeteer
FROM apify/actor-node-puppeteer-chrome:18

# Copy package.json and package-lock.json
COPY package*.json ./

# Install NPM packages
RUN npm --quiet set progress=false \
    && npm install --omit=dev --omit=optional \
    && echo "Installed NPM packages:" \
    && (npm list --omit=dev --all || true) \
    && echo "Node.js version:" \
    && node --version \
    && echo "NPM version:" \
    && npm --version \
    && rm -r ~/.npm

# Copy source code
COPY . ./

# Set the command to start the actor
CMD npm start